### ISSUE TITLE
[General Question] Declaring connection between function with endpoints and tables?

### ISSUE THREAD

**Issue by mpetyx** [capless/sammy#1]
Hey!!
Amazing job with this library.
I am playing with it a little bit, and wanted to understand it deeper.
Is there a way to declare that a specific function is related to a table and this function is related to an API Gateway endpoint?

Can I also use variables?

Let's say I want to say that whenever you run the script, a table x is connected with permissions to a function y and this is the backend for function xy.

Cheers,
Michael.

**Comment by bjinwright** [comment]
**Question: Is there a way to declare that a specific function is related to a table and this function is related to an API Gateway endpoint?**

I'm currently working on flushing out [event types](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#event-source-types), [property types](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#property-types), and output values

**Comment by bjinwright** [comment]
You can now use event types, property types, variables in version 0.2.0. Output values will be in 0.3.0.
